import math
import re
import json
import ollama

def safe_json_decode_python(text):
    """
    Safely attempts to parse JSON from a string generated by LLMs.
    Handles markdown code blocks and invalid multiline strings.
    """
    if not text:
        return None
        
    text = re.sub(r'^```json\s*', '', text, flags=re.MULTILINE)
    text = re.sub(r'^```\s*$', '', text, flags=re.MULTILINE)
    text = text.strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r'\{.*\}', text, flags=re.DOTALL)
    if not match:
        return None
        
    json_str = match.group(0)

    json_str = re.sub(r',\s*\}', '}', json_str)
    json_str = re.sub(r',\s*\]', ']', json_str)
    
    def escape_newlines(m):
        return m.group(0).replace('\n', '\\n').replace('\r', '\\r')
    
    json_str = re.sub(r'(?<!\\)".*?(?<!\\)"', escape_newlines, json_str, flags=re.DOTALL)

    try:
        return json.loads(json_str)
    except json.JSONDecodeError as e:
        print(f"Failed to parse extracted JSON: {e}\nRaw string:\n{json_str[:200]}...")
        return None

def identify_conflict2(book_name, sentences, max_tokens=1000, model="mistral-small3.2:24b"): # mistral-large-3:675b-cloud
    """
    Agent 1: Determines the core story conflict of the passages using strict JSON Schema.
    """
    conflict_schema = {
        "type": "object",
        "properties": {
            "analysis_scratchpad": {
                "type": "string",
                "description": "Step-by-step analysis of the provided text. Identify the characters present IN THIS TEXT ONLY and their immediate goals/fears in these specific passages."
            },
            "core_conflict": {
                "type": "string",
                "description": "The main conflict of the scene in 1-2 sentences. No literary analysis."
            },
            "sub_conflicts": {
                "type": "array",
                "items": {"type": "string"},
                "description": "List of up to 3 sub-conflicts."
            }
        },
        "required": ["analysis_scratchpad", "core_conflict", "sub_conflicts"]
    }
    
    prompt = (
        f"You are analyzing a single chapter or scene from '{book_name}'.\n"
        "You will be given a list of short passages.\n"
        "Your task is to identify the story conflict, not the literary theme.\n\n"
        "RULES:\n"
        "- Describe only what the characters want, fear, or are trying to prevent.\n"
        "- Do not mention themes, motifs, or messages.\n"
        "- Write 1 or 2 sentences for the core_conflict.\n"
        "- Optionally, write up to 3 short sub_conflicts if they clearly affect the main one.\n"
        "- Avoid using double quotes (\") inside your text strings.\n\n"

        "- Do NOT reuse examples or content from any previous tasks or books.\n"
        "- Only use the passages shown below as your source.\n"

        f'''You must respond ONLY with a valid JSON object. 
        Do NOT use raw newlines inside JSON string values. Use \\n instead.
        Your JSON must strictly follow this exact schema:
        {json.dumps(conflict_schema, indent=2)}'''
        "Passages:\n"
    )

    for ind, s in enumerate(sentences):
        prompt += f"[{ind}] {s}\n"

    try:
        response = ollama.generate(
            model=model,
            prompt=prompt,
            think=False,
            keep_alive='2m',
            format='json', 
            options={
                'temperature': 0,
                'num_predict': max_tokens,
                "num_ctx": 262144
            }
        )
        
        text = response.response.strip()

        parsed_json = safe_json_decode_python(text)

        
    except Exception as e:
        print(f"Generation error for {book_name}: {e}")
        parsed_json = None
    
    if not parsed_json or not isinstance(parsed_json, dict) or "core_conflict" not in parsed_json:
        parsed_json = {
            "core_conflict": "Main characters are involved in a sequence of events.", 
            "sub_conflicts": []
        }
        
    return parsed_json

def process_short_text(book_name, sentences, model='mistral-small3.2:24b', max_tokens=1000):

    short_schema = {
        "type": "object",
        "properties": {
            "top_4_events": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Exactly 4 sentences describing the literal physical actions in order. NO ABSTRACT WORDS."
            }
        },
        "required": ["top_4_events"]
    }
    
    prompt = (
        f"Analyze this specific excerpt from '{book_name}'.\n"
        "Your task is to identify the 4 most important literal narrative events happening IN THIS EXCERPT ONLY.\n\n"
        "RULES:\n"
        "- DO NOT write a thematic essay, summary, or literary analysis.\n"
        "- DO NOT use abstract words (e.g., 'internal struggle', 'turmoil', 'conflict').\n"
        "- Describe ONLY concrete physical actions, specific dialogue points, or plot movements.\n"
        "- If the text is purely philosophical, state: 'No narrative events.'\n\n"

        "- Do NOT reuse examples or content from any previous tasks or books.\n"
        "- Only use the passages shown below as your source.\n"

        f'''You must respond ONLY with a valid JSON object. 
        Do NOT use raw newlines inside JSON string values. Use \\n instead.
        Your JSON must strictly follow this exact schema:
        {json.dumps(short_schema, indent=2)}'''
        "Excerpt:\n"
    )

    for ind, s in enumerate(sentences):
        prompt += f"[{ind}] {s}\n"

    

    try:
        response = ollama.generate(
            model=model,
            prompt=prompt,
            think=False,
            keep_alive='2m',
            format='json',
            options={'temperature': 0.0, 'num_predict': max_tokens, "num_ctx": 262144}
        )
        
        parsed = safe_json_decode_python(response.response.strip())
        
        if parsed and "top_4_events" in parsed and len(parsed["top_4_events"]) > 0:
            events = parsed["top_4_events"]
            if "No narrative events" in events[0]:
                return {"analysis_scratchpad": "No physical events.", "core_conflict": "No narrative events.", "sub_conflicts": []}
                
            core_text = " ".join(events[:2])
            subs = events[2:] if len(events) > 2 else []
            
            return {
                "analysis_scratchpad": "Events merged from local excerpts.",
                "core_conflict": core_text,
                "sub_conflicts": subs
            }
    except Exception:
        pass
        
    return {"analysis_scratchpad": "Fallback", "core_conflict": "Main characters are involved in a sequence of events.", "sub_conflicts": []}

def extract_local_conflict(book_name, chunk_sentences, model='mistral-small3.2:24b', max_tokens=768):
    local_schema = {
        "type": "object",
        "properties": {
            "analysis_scratchpad": {
                "type": "string",
                "description": "Briefly list the characters and their literal actions. If none, write 'No actions'."
            },
            "core_conflict": {
                "type": "string",
                "description": "1-2 sentences explaining the main plot event or character conflict in this excerpt."
            },
            "sub_conflicts": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Up to 3 specific sub-events or interactions."
            }
        },
        "required": ["analysis_scratchpad", "core_conflict", "sub_conflicts"]
    }
    
    prompt = (
        f"Analyze this specific excerpt from '{book_name}'.\n"
        "Your task is to identify the literal narrative events happening IN THIS EXCERPT ONLY.\n\n"
        "RULES:\n"
        "- DO NOT write a thematic essay or literary analysis.\n"
        "- Describe only physical actions, character interactions, or specific plot points.\n"
        "- If the text is merely a list (e.g., list of books/titles) or purely philosophical without character action, state: 'No narrative events in this excerpt.'\n\n"

        "- Do NOT reuse examples or content from any previous tasks or books.\n"
        "- Only use the passages shown below as your source.\n"
    
        f'''You must respond ONLY with a valid JSON object. 
        Do NOT use raw newlines inside JSON string values. Use \\n instead.
        Your JSON must strictly follow this exact schema:
        {json.dumps(local_schema, indent=2)}'''
        "Excerpt:\n"
    )

    for ind, s in enumerate(chunk_sentences):
        prompt += f"[{ind}] {s}\n"

    try:
        response = ollama.generate(
            model=model,
            prompt=prompt,
            think=False,
            keep_alive='2m',
            format='json',
            options={'temperature': 0.0, 'num_predict': max_tokens, "num_ctx": 262144}
        )
        return safe_json_decode_python(response.response.strip())
    except Exception:
        return None

def merge_conflicts(book_name, local_conflicts, model='mistral-small3.2:24b', max_tokens=768):
    """
    Умный Reduce: Не просим писать 'summary'. Просим просто выбрать 4 главных факта.
    """
    reduce_schema = {
        "type": "object",
        "properties": {
            "top_4_events": {
                "type": "array",
                "items": {"type": "string"},
                "description": "Exactly 4 sentences describing the most important physical actions in chronological order. NO ABSTRACT WORDS."
            }
        },
        "required": ["top_4_events"]
    }
    
    prompt = (
        f"You are given a list of literal events from the '{book_name}'.\n"
        "Your ONLY task is to select the 4 most important physical events from this list that span the beginning, middle, and end of the story.\n\n"
        "RULES:\n"
        "- DO NOT write a summary or essay.\n"
        "- DO NOT use abstract words (e.g., satire, themes, conflict, institutions).\n"
        "- Just copy or slightly rephrase the concrete actions (e.g., 'Pantagruel goes to Paris').\n\n"

        "- Do NOT reuse examples or content from any previous tasks or books.\n"
        "- Only use the passages shown below as your source.\n"

        f'''You must respond ONLY with a valid JSON object. 
        Do NOT use raw newlines inside JSON string values. Use \\n instead.
        Your JSON must strictly follow this exact schema:
        {json.dumps(reduce_schema, indent=2)}'''
        "List of Events:\n"
    )

    valid_parts_count = 0
    for i, conf in enumerate(local_conflicts):
        if conf and 'core_conflict' in conf and "No narrative events" not in conf['core_conflict'] and "No physical conflict" not in conf['core_conflict']:
            valid_parts_count += 1
            prompt += f"Event {valid_parts_count}: {conf['core_conflict']}\n"
            for sub in conf.get('sub_conflicts', []):
                prompt += f" - {sub}\n"
        prompt += "\n"

    if valid_parts_count == 0:
        return {
            "analysis_scratchpad": "No valid events.",
            "core_conflict": "The text consists of philosophical descriptions without character action.",
            "sub_conflicts": []
        }

    

    try:
        response = ollama.generate(
            model=model,
            prompt=prompt,
            think=False,
            keep_alive='2m',
            format='json',
            options={'temperature': 0.0, 'num_predict': max_tokens, "num_ctx": 262144}
        )
        
        parsed = safe_json_decode_python(response.response.strip())
        
        if parsed and "top_4_events" in parsed and len(parsed["top_4_events"]) > 0:
            events = parsed["top_4_events"]
            
            core_text = " ".join(events[:2])
            subs = events[2:] if len(events) > 2 else []
            
            return {
                "analysis_scratchpad": "Events merged from local excerpts.",
                "core_conflict": core_text,
                "sub_conflicts": subs
            }
        else:
            raise ValueError("Missing top_4_events in JSON")
            
    except Exception as e:
        print(f"Error in merge_conflicts: {e}")
        return {
            "analysis_scratchpad": "Fallback due to JSON error.",
            "core_conflict": "Main characters are involved in a sequence of events.",
            "sub_conflicts": []
        }

def identify_conflict(book_name, sentences, max_tokens=2000, model="mistral-small3.2:24b", max_words_per_chunk=1800): #mistral-large-3:675b-cloud
    """
    Agent 1 (Main): Determines the core story conflict with a Map-Reduce approach for long texts.
    """
    conflict_schema = {
        "type": "object",
        "properties": {
            "analysis_scratchpad": {
                "type": "string",
                "description": "Step-by-step literal analysis of characters' physical actions and immediate goals in the provided text. NO literary theory."
            },
            "core_conflict": {
                "type": "string",
                "description": "The main literal conflict in 1-2 sentences. No thematic analysis."
            },
            "sub_conflicts": {
                "type": "array",
                "items": {"type": "string"},
                "description": "List of up to 3 physical or interpersonal sub-conflicts."
            }
        },
        "required": ["analysis_scratchpad", "core_conflict", "sub_conflicts"]
    }

    total_words = sum(len(s.split()) for s in sentences)
    
    if total_words <= max_words_per_chunk:
        result = identify_conflict2(book_name, sentences) 
    else:
        # MAP-REDUCE для длинных текстов
        print(f"Text is too long ({total_words} words). Chunking for identify_conflict...")
        chunks = []
        current_chunk = []
        current_words = 0
        
        for s in sentences:
            s_words = len(s.split())
            if current_words + s_words > max_words_per_chunk and current_chunk:
                chunks.append(current_chunk)
                current_chunk = [s]
                current_words = s_words
            else:
                current_chunk.append(s)
                current_words += s_words
        if current_chunk:
            chunks.append(current_chunk)
            
        local_conflicts = []
        for chunk in chunks:
            res = extract_local_conflict(book_name, chunk, model, max_tokens)
            if res:
                local_conflicts.append(res)
                
        if local_conflicts:
            result = merge_conflicts(book_name, local_conflicts, model, max_tokens)
        else:
            result = None

    if not result or not isinstance(result, dict) or "core_conflict" not in result:
        result = {
            "core_conflict": "Main characters are involved in a sequence of events.", 
            "sub_conflicts": []
        }
        
    return result